### PR TITLE
zh translation

### PR DESCRIPTION
**Pull request by Mortis66666**
I'm bored, so I decided to translate this to Chinese.

### CODE REVIEW

**Comment by Daenyth** [comment]
👍 I'll find some people to review it once you're done with draft

**Comment by Mortis66666** [comment]
Finally finish translated all the pages, it's a long run. Some pages like x1 and x2 is still untranslated because I have other things to do, so good luck to the next person (I might translate it in the future if no one does).

Something worth mentioning, according to [Wikipedia](https://zh.wikipedia.org/wiki/道本语), toki pona is translated to 道本语. I'm not sure if I should put that instead of the word "toki pona", but for consistency, I decided to leave it as "toki pona". I also changed the indexing number for the pages from Chinese to Arabic numbers, because 第七a页 is very unaesthetic.

Also, in page 10 line 45:
> As a pre-verb, the word "**ken**" functions much like the English word "can":

When translating this, I wonder if I should just hard-translate it, or actually change it to Chinese perspective, so I referred to the Esperanto translation, and realize it hard-translated it, so I do the same. Then I realized that kinda defeats the purpose of translating as people who read the translated text are not familiar to English, plus I checked German and Russian translation and those translated "can" to their native word for "can", so I decided to do the same.

I do found some minor issue while translating, I guess I will create an issue for that.

**Comment by 0xis-cn** [comment]
If the PR is pending I will consider deploying it separately on GitHub Pages

**Comment by Daenyth** [comment]
I reached out to people again asking to review, since I'm not able to speak the language

**Comment by cubedhuang** [comment]
^^ above are copied changes from jan lili Enta that he sent in kama sona

also note: add the link to Chinese page on main index page when you're ready

**Pull request merged**
