### PR TITLE
pt translation

### PR DESCRIPTION
**Pull request by aliceofmeiji**

### CODE REVIEW

**Comment by slashdevslashurandom** [comment]
Seems OK to me, with only one slight issue: other translated versions of the LSP pages are just in the `pages` directory, they aren't placed in a separate directory.

If you could move `pages/pt/*` to just `pages/`, that would be nice.

**Review by slashdevslashurandom — APPROVED** [review]
Looks good to me.

**Comment by slashdevslashurandom** [comment]
@aliceofmeiji How would you like to be credited in the translations list?

**Comment by aliceofmeiji** [comment]
> @aliceofmeiji How would you like to be credited in the translations list?

id love that :)

**Comment by slashdevslashurandom** [comment]
Sorry, but the question is **how** you would like to be credited? When I add the new translation to the table at the main index page, how should I refer to you as the translation's author (and optionally -- would you want that name to also be a link to some profile page of yours)?

**Comment by aliceofmeiji** [comment]
> Sorry, but the question is **how** you would like to be credited? When I add the new translation to the table at the main index page, how should I refer to you as the translation's author (and optionally -- would you want that name to also be a link to some profile page of yours)?

ohhh, sorry i misread

"jan Alise - Alice de Paula" is good

**Pull request merged**
